name: Daily MarineTraffic Fetch

on:
  schedule:
    - cron: "0 5 * * *"  # runs daily at 05:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python marine_fetch.py

      - name: Commit XML file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.xml
          git commit -m "📦 Daily MarineTraffic fetch"
          git push
